[project]
name = "multimodal-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lxml>=5.4.0",
    "pandas>=2.2.3",
    "sentence-transformers>=4.1.0",
    "transformers>=4.51.3",
]
